In [651]:
# from google.colab import drive
# drive.mount("/content/drive")

In [652]:
# !pip install pdfplumber -q
# !apt-get install ocrmypdf -q   #installing OCR library 

In [653]:
# import pdfplumber
import pandas as pd
import numpy as np
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords 
from string import punctuation
from nltk.corpus import wordnet as wn
from nltk.stem import WordNetLemmatizer
from nltk.probability import FreqDist
from heapq import nlargest
from collections import defaultdict
import pandas as pd 
from nltk.collocations import *
nltk.download('punkt')
nltk.download('stopwords')
# nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\INES\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\INES\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [654]:
# with pdfplumber.open("/content/drive/MyDrive/test.pdf") as pdf:
#     text=""
#     pages = pdf.pages
#     for page in pages:
#         text += page.extract_text(x_tolerance=2)
#         print(text)

# Import CV and scraped data

In [655]:
# Import CV
# f=open(r"C:\ikhsan\UNAIR\MBKM\Bangkit\Profile.pdf",'r', errors = 'ignore')
# text=f.read()

import pdfminer
from pdfminer.high_level import extract_text

# Read PDF file and extract text
def read_pdf(file_path):
    text = extract_text(file_path)
    # print(text)
    return text

# Preprocess text
def preprocess_text(text):
    # Implement text preprocessing steps as per your requirements
    # For example, remove special characters, convert to lowercase, etc.
    # print(text)
    return text

resume_path = r"C:\ikhsan\UNAIR\Template CV ATS-Friendly Glints\CV panjang.pdf"
resume_text = read_pdf(resume_path)
text = preprocess_text(resume_text)

# Locations
f1=open(r"C:\ikhsan\UNAIR\MBKM\Bangkit\1. Capstone\Location.txt",'r', errors = 'ignore')
text1=f1.read()
locations = word_tokenize(text1.replace("\n", " "))

# Additional stopwords
f2=open(r"C:\ikhsan\UNAIR\MBKM\Bangkit\1. Capstone\stopwords.txt",'r', errors = 'ignore')
text2=f2.read()
stopwords_additional = word_tokenize(text2.replace("\n", " "))

In [656]:
def nlp(x):
    word_sent = word_tokenize(x.lower().replace("\n",""))
    _stopwords = set(stopwords.words('english', 'indonesian') + list(punctuation)+list("●")+list('–')+list('’')+locations+stopwords_additional)
    word_sent=[word for word in word_sent if word not in _stopwords]
    lemmatizer = WordNetLemmatizer()
    NLP_Processed_CV = [lemmatizer.lemmatize(word) for word in word_tokenize(" ".join(word_sent))]
#     return " ".join(NLP_Processed_CV)
    return NLP_Processed_CV

In [657]:
def get_key_word(x):
    finder = BigramCollocationFinder.from_words(x)
    lst = []
    Key_word_from_CV = []
    for i in sorted(finder.ngram_fd.items()):
    # if a double word appears more than once, then print it out.
        if i[1] > 1:
            print(i)
            lst.append(i[0])
        else:
            pass

    # print("************************")
    for j in lst:
    #     print(" ".join(j))
        Key_word_from_CV.append(" ".join(j))
    return Key_word_from_CV

In [658]:
NLP_Processed_CV = nlp(text)
# NLP_Processed_CV=' '.join(NLP_Processed_CV)
NLP_Processed_CV

['hubungicampursalam',
 'parakan',
 'temanggung085802754354',
 'mobile',
 'ikhsan2050',
 'gmail.commukhamad',
 'ikhsanudinsistem',
 'informasi',
 'universitas',
 'airlangga',
 "mas'ul",
 'jimm',
 'fst',
 '2022',
 '|bem',
 'fst',
 '2023',
 'kampus',
 'merdeka',
 'bangkit',
 '2023',
 'studenttemanggung',
 'jawa',
 'tengah',
 'indonesiawww.linkedin.com/in/ikhsanudin',
 'linkedin',
 'ringkasankeahlian',
 'teratasmachine',
 'learningpython',
 'programming',
 'language',
 'canvalanguagesbahasa',
 'jawa',
 'native',
 'bilingual',
 'bahasa',
 'indonesia',
 'native',
 'orbilingual',
 'certificationsbelajar',
 'dasar',
 'git',
 'dengan',
 'githubprepare',
 'data',
 'explorationbelajar',
 'dasar',
 'visualisasi',
 'dataprocess',
 'data',
 'dirty',
 'cleanintroduction',
 'packet',
 'tracerhonors-awardsperingkat',
 '1',
 'karya',
 'tulis',
 'ilmiah',
 "al-qur'an",
 'mtqmmahasiswa',
 'aktif',
 'program',
 'studi',
 'sistem',
 'informasi',
 'fakultas',
 'sainsdan',
 'teknologi',
 'universitas',
 'air

In [659]:
key_word = get_key_word(NLP_Processed_CV)
key_word

(('bulan', 'mempelajari'), 2)
(('sistem', 'informasi'), 2)


['bulan mempelajari', 'sistem informasi']

In [660]:
#Import scraped data
df = pd.read_excel(r"C:\ikhsan\UNAIR\MBKM\Bangkit\1. Capstone\data website indeed Jakarta (data 30 May 2023).xlsx", "clean data")
index = []
for i in range (0, len(df)):
    index.append(i)
df.insert(0,'JobID', index)
df['All'] = df['Posisi'] + ' ' + df['Perusahaan '] + ' ' + df['Lokasi'] + ' ' + df['Tipe Pekerjaan'] + ' ' + df['Kualifikasi'] + ' ' + df['Deskripsi Pekerjaan ']
df.head(2)

JobID                               Posisi                Perusahaan    
0      0  Talent Host Streaming ( Freelance )  THE AESTHETIC SKIN CLINIC  \
1      1                         Data Analyst                   Peroptyx   

    Lokasi  Salary (minimum per bulan) Tipe Pekerjaan   
0  Jakarta                           0      Part-time  \
1  Jakarta                     1653356      Part-time   

                                         Kualifikasi   
0  Wanita\nUsia maksimal 30 tahun\nMemiliki penga...  \
1  Technical requirements to perform the work\nAc...   

                                Deskripsi Pekerjaan    
0  Melakukan penjualan produk secara live di Tik ...  \
1  Work up to 20 hours per week.\nEarn a competit...   

                                                Link   
0  https://id.indeed.com/company/The-Aesthetic-Sk...  \
1  https://id.indeed.com/pagead/clk?mo=r&ad=-6NYl...   

                                                 All  
0  Talent Host Streaming ( Freelance ) THE AESTHE...  
1  Data Analyst Peroptyx Jakarta Part-time Techni...

In [661]:
# print(NLP_Processed_CV)
# print(key_word)
df.shape

(312, 10)

In [662]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 312 entries, 0 to 311
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype 
---  ------                      --------------  ----- 
 0   JobID                       312 non-null    int64 
 1   Posisi                      312 non-null    object
 2   Perusahaan                  312 non-null    object
 3   Lokasi                      312 non-null    object
 4   Salary (minimum per bulan)  312 non-null    int64 
 5   Tipe Pekerjaan              312 non-null    object
 6   Kualifikasi                 312 non-null    object
 7   Deskripsi Pekerjaan         171 non-null    object
 8   Link                        312 non-null    object
 9   All                         171 non-null    object
dtypes: int64(2), object(8)
memory usage: 24.5+ KB


In [663]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(decode_error='replace', encoding='utf-8', stop_words=stopwords.words('english', 'indonesian'))
tfidf_jobid = tfidf_vectorizer.fit_transform(df['All'].apply(lambda tfidf_jobid: np.str_(tfidf_jobid)))
# print(tfidf_jobid)
user_tfidf = tfidf_vectorizer.transform(df['All'].apply(lambda user_tfidf: np.str_(user_tfidf)))

In [664]:
cos_similarity_tfidf = map(lambda x: cosine_similarity(user_tfidf,x),tfidf_jobid)
output2 = list(cos_similarity_tfidf)
output2

[array([[1.        ],
        [0.02094292],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.0952672 ],
        [0.13116673],
        [0.04095645],
        [0.39483302],
        [0.14657774],
        [0.        ],
        [0.09716857],
        [0.        ],
        [0.10076995],
        [0.        ],
        [0.12141341],
        [0.07217102],
        [0.0764824 ],
        [0.13250845],
        [0.01384515],
        [0.1556581 ],
        [0.14874999],
        [0.        ],
        [0.16374915],
        [0.10358395],
        [0.02405109],
        [0.        ],
        [0.        ],
        [0.02098931],
        [0.        ],
        [0.11519077],
        [0.        ],
        [0.11877745],
        [0.        ],
        [0.15876943],
        [0.21909111],
        [0.        ],
        [0.        ],
        [0.08160977],
        [0.11418817],
        [0.11620351],
        [0.        ],
        [0.05658806],
        [0.27338424],
        [0.09743825],
        [0

In [665]:
# from sklearn.metrics.pairwise import cosine_similarity
# from sklearn.feature_extraction.text import TfidfVectorizer
# def TFIDF(scraped_data, cv):
#     tfidf_vectorizer = TfidfVectorizer(stop_words=stopwords.words('indonesian'))

#     # TF-IDF Scraped data
#     tfidf_jobid = tfidf_vectorizer.fit_transform(scraped_data)

#     # TF-IDF CV
#     user_tfidf = tfidf_vectorizer.transform(cv)

#     # Using cosine_similarity on (Scraped data) & (CV)
#     cos_similarity_tfidf = map(lambda x: cosine_similarity(user_tfidf,x),tfidf_jobid)

#     output2 = list(cos_similarity_tfidf)
#     return output2
    
# output2 = TFIDF(df['All'], df2['All'])
# output2

# Put keyword/CV into a dataframe

In [666]:
df2 = pd.DataFrame()
# append columns to an empty DataFrame
df2['title'] = ["I"]
df2['job highlights'] = ["I"]
df2['job description'] = ["I"]
df2['company overview'] = ["I"]
df2['industry'] = ["I"]

# Compare with the key words from CV only
df2['All'] = " ".join(key_word)
df2.head(2)
# Compare with the entire CV
# df2['All'] = " ".join(NLP_Processed_CV)
# df2

title job highlights job description company overview industry   
0     I              I               I                I        I  \

                                  All  
0  bulan mempelajari sistem informasi

# Create get_recommendation function

In [667]:
def get_recommendation(top, df_all, scores):
    recommendation = pd.DataFrame(columns = ['JobID',  'title', 'industry', 'job description','score'])
    count = 0
    for i in top:
#         recommendation.at[count, 'ApplicantID'] = u
        recommendation.at[count, 'JobID'] = df.index[i]
        recommendation.at[count, 'title'] = df['Posisi'][i]
        recommendation.at[count, 'industry'] = df['Perusahaan '][i]
#         recommendation.at[count, 'location'] = df['location'][i]
        recommendation.at[count, 'job description'] = df['Deskripsi Pekerjaan '][i]
        recommendation.at[count, 'score'] =  scores[count]
        count += 1
    return recommendation

# TFIDF

In [668]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

def TFIDF(scraped_data, cv):
    tfidf_vectorizer = TfidfVectorizer(decode_error='replace', encoding='utf-8', stop_words=stopwords.words('english', 'indonesian'))

    # TF-IDF Scraped data
    tfidf_jobid = tfidf_vectorizer.fit_transform(scraped_data.apply(lambda x: np.str_(x)))
    # tfidf_jobid = tfidf_vectorizer.fit_transform(scraped_data)

    # TF-IDF CV
    user_tfidf = tfidf_vectorizer.transform(cv.apply(lambda x: np.str_(x)))
    # user_tfidf = tfidf_vectorizer.transform(cv)

    # Using cosine_similarity on (Scraped data) & (CV)
    cos_similarity_tfidf = map(lambda x: cosine_similarity(user_tfidf,x),tfidf_jobid)

    output2 = list(cos_similarity_tfidf)
    return output2
    
output2 = TFIDF(df['All'], df2['All'])
output2

[array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.03156128]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.0425374]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.02857255]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.06945544]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.03852872]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.03016507]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[

In [669]:
top = sorted(range(len(output2)), key=lambda i: output2[i], reverse=True)[:100]
list_scores = [output2[i][0][0] for i in top]
TF=get_recommendation(top,df, list_scores)
TF

JobID                             title   
0    265                 Guru/Totur Bahasa  \
1     35  Beauty Advisor - Innisfree Store   
2    304                  Host Live Tiktok   
3    104   Host Live Streaming TikTok Shop   
4    306                  Asisten Apoteker   
..   ...                               ...   
95    69            Tutor Bahasa Indonesia   
96    70                Admin Social Media   
97    72                      Staff Gudang   
98    73                           Florist   
99    75        FIELD COLLECTION PELALAWAN   

                                            industry   
0                           Bimbel Nusantara belajar  \
1                                 Time International   
2                                FCOMMERCE INDONESIA   
3   Future Commerce Indonesia (F-Commerce Indonesia)   
4                                 Apotek Alfa Medika   
..                                               ...   
95                   Brain Academy Center Petukangan   
96                             PT. Kencana Panelindo   
97                       PT Asia Garments Accesories   
98                     PT Lumiere Berkembang Bersama   
99                          PT Home Credit Indonesia   

                                      job description     score  
0   Mengajar siswa secara tatap muka\nMengevaluasi...  0.082467  
1   Melayani customer dengan baik dan ramah \nDapa...  0.069455  
2   Bertanggung jawab atas Live streaming sehari-h...  0.062194  
3   Bertanggung jawab atas Live streaming sehari-h...  0.060049  
4   Membaca dan meracik obat\nMelayani pembelian p...  0.059236  
..                                                ...       ...  
95                                                NaN       0.0  
96  Merencanakan konten apa saja yang akan dibuat ...       0.0  
97  Memastikan ketersedian barang di gudang \nmenc...       0.0  
98             Merangkai bunga untuk pesanan customer       0.0  
99  Mengunjungi Customer sesuai dengan daftar yang...       0.0  

[100 rows x 5 columns]

# Count Vectorizer

In [670]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# print(tfidf_jobid)
user_tfidf = tfidf_vectorizer.transform(df['All'].apply(lambda user_tfidf: np.str_(user_tfidf)))

def count_vectorize(scraped_data, cv):
    # CountV the scraped data
    # count_vectorizer = CountVectorizer()
    count_vectorizer = CountVectorizer(decode_error='replace', encoding='utf-8', stop_words=stopwords.words('english', 'indonesian'))
    # count_jobid = count_vectorizer.fit_transform(scraped_data) #fitting and transforming the vector
    count_jobid = count_vectorizer.fit_transform(scraped_data.apply(lambda x: np.str_(x)))

    # CountV the cv
    # user_count = count_vectorizer.transform(cv)
    user_count = count_vectorizer.transform(cv.apply(lambda x: np.str_(x)))
    cos_similarity_countv = map(lambda x: cosine_similarity(user_count, x),count_jobid)
    output3 = list(cos_similarity_countv)
    return output3
output3 = count_vectorize(df['All'], df2['All'])
output3

[array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.03325951]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.0308901]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.03149704]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.04642383]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.04003204]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.02901294]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[

In [671]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

count_vectorizer = CountVectorizer(decode_error='replace', encoding='utf-8', stop_words=stopwords.words('english', 'indonesian'))
count_jobid = count_vectorizer.fit_transform(df['All'].apply(lambda x: np.str_(x))) #fitting and transforming the vector
count_jobid


<312x3044 sparse matrix of type '<class 'numpy.int64'>'
	with 12458 stored elements in Compressed Sparse Row format>

In [672]:
# print(count_jobid)

In [673]:
user_count = count_vectorizer.transform(df2['All'].apply(lambda x: np.str_(x)))
user_count

<1x3044 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [674]:
print(user_count)

  (0, 413)	1
  (0, 1111)	1
  (0, 1644)	1
  (0, 2610)	1


In [675]:
cos_similarity_countv = map(lambda x: cosine_similarity(user_count, x),count_jobid)
output3 = list(cos_similarity_countv)
output3

[array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.03325951]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.0308901]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.03149704]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.04642383]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.04003204]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.02901294]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[

In [676]:
# output3 = count_vectorize(df['All'], df2['All'])
# output3

In [677]:
top = sorted(range(len(output3)), key=lambda i: output3[i], reverse=True)[:100]
list_scores = [output3[i][0][0] for i in top]
cv=get_recommendation(top, df, list_scores)
cv

JobID                                              title   
0    306                                   Asisten Apoteker  \
1    265                                  Guru/Totur Bahasa   
2     74                                  Staff Maintanance   
3    279  Senior Cook Indonesian Food (Balinese) - Jakar...   
4    276                                   Internship Sales   
..   ...                                                ...   
95    69                             Tutor Bahasa Indonesia   
96    70                                 Admin Social Media   
97    72                                       Staff Gudang   
98    73                                            Florist   
99    75                         FIELD COLLECTION PELALAWAN   

                               industry   
0                    Apotek Alfa Medika  \
1              Bimbel Nusantara belajar   
2            PT Recruit First Indonesia   
3             PT Boga Inti (Boga Group)   
4   CV. Aneka Cipta Informasi Solusindo   
..                                  ...   
95      Brain Academy Center Petukangan   
96                PT. Kencana Panelindo   
97          PT Asia Garments Accesories   
98        PT Lumiere Berkembang Bersama   
99             PT Home Credit Indonesia   

                                      job description     score  
0   Membaca dan meracik obat\nMelayani pembelian p...  0.076249  
1   Mengajar siswa secara tatap muka\nMengevaluasi...  0.075378  
2   Melakukan pengecekan unit \nMemelihara keadaan...  0.058926  
3   Bertanggung jawab dalam mengendalikan waste di...   0.04969  
4   Melakukan prospekting data customer\nDapat ber...  0.047891  
..                                                ...       ...  
95                                                NaN       0.0  
96  Merencanakan konten apa saja yang akan dibuat ...       0.0  
97  Memastikan ketersedian barang di gudang \nmenc...       0.0  
98             Merangkai bunga untuk pesanan customer       0.0  
99  Mengunjungi Customer sesuai dengan daftar yang...       0.0  

[100 rows x 5 columns]

# KNN

In [678]:
from sklearn.neighbors import NearestNeighbors

def KNN(scraped_data, cv):
    tfidf_vectorizer = TfidfVectorizer(decode_error='replace', encoding='utf-8', stop_words=stopwords.words('english', 'indonesian'))

    n_neighbors = 100
    KNN = NearestNeighbors()
    KNN.fit(tfidf_vectorizer.fit_transform(scraped_data.apply(lambda x: np.str_(x))))
#     NNs = KNN.kneighbors(tfidf_vectorizer.transform(cv), return_distance=True)
    NNs = KNN.kneighbors(tfidf_vectorizer.transform(cv.apply(lambda x: np.str_(x))))
    top = NNs[1][0][1:]
    index_score = NNs[0][0][1:]

    knn = get_recommendation(top, df, index_score)
    return knn

knn = KNN(df['All'], df2['All'])
knn

JobID                             title   
0    35  Beauty Advisor - Innisfree Store  \
1   304                  Host Live Tiktok   
2   104   Host Live Streaming TikTok Shop   
3   306                  Asisten Apoteker   

                                           industry   
0                                Time International  \
1                               FCOMMERCE INDONESIA   
2  Future Commerce Indonesia (F-Commerce Indonesia)   
3                                Apotek Alfa Medika   

                                     job description     score  
0  Melayani customer dengan baik dan ramah \nDapa...  1.364217  
1  Bertanggung jawab atas Live streaming sehari-h...   1.36953  
2  Bertanggung jawab atas Live streaming sehari-h...  1.371095  
3  Membaca dan meracik obat\nMelayani pembelian p...  1.371688

In [679]:
knn.to_csv('knn.csv', index=False)

# Combined TFIDF, CV and KNN result together, to make a dataframe "final"

In [680]:
# merge1 = knn[['JobID','title', 'score']].merge(TF[['JobID','score']], on= "JobID")
# final = merge1.merge(cv[['JobID','score']], on = "JobID")
# final = final.rename(columns={"score_x": "KNN", "score_y": "TF-IDF","score": "CV"})
# final.head()

merge1 = knn[['JobID','title', 'score']].merge(TF[['JobID','score']], on= "JobID")
final = merge1.merge(cv[['JobID','score']], on = "JobID")
final = final.rename(columns={"score_x": "KNN", "score_y": "TF-IDF","score": "CV"})
final.head()

JobID                             title       KNN    TF-IDF        CV
0    35  Beauty Advisor - Innisfree Store  1.364217  0.069455  0.046424
1   304                  Host Live Tiktok   1.36953  0.062194  0.043073
2   104   Host Live Streaming TikTok Shop  1.371095  0.060049   0.04207
3   306                  Asisten Apoteker  1.371688  0.059236  0.076249

In [681]:
# high = max(knn['score'])
# def reverseScoring(df, high, cols):
#     '''Reverse scores on given columns
#      df = your data frame,
#      high = highest score available
#      cols = the columns you want reversed in list form'''
#     df[cols] = high - df[cols]
# #     return df['score']
#     return df
# reverseScoring(knn, high, 'score')

In [682]:
# reverseScoring(knn, high, 'score').to_csv('test.csv', index=False)

# Scale and assign weights

In [683]:
# Scale it
from sklearn.preprocessing import MinMaxScaler
slr = MinMaxScaler()
final[["KNN", "TF-IDF", 'CV']] = slr.fit_transform(final[["KNN", "TF-IDF", 'CV']])

# Multiply by weights
final['KNN'] = (1-final['KNN'])/3
final['TF-IDF'] = final['TF-IDF']/3
final['CV'] = final['CV']/3
final['Final'] = final['KNN']+final['TF-IDF']+final['CV']
final.sort_values(by="Final", ascending=False)

JobID                             title       KNN    TF-IDF        CV   
0    35  Beauty Advisor - Innisfree Store  0.333333  0.333333  0.042458  \
3   306                  Asisten Apoteker  0.000000  0.000000  0.333333   
1   304                  Host Live Tiktok  0.096300  0.096487  0.009779   
2   104   Host Live Streaming TikTok Shop  0.026454  0.026520  0.000000   

      Final  
0  0.709125  
3  0.333333  
1  0.202566  
2  0.052974

In [684]:
# final.to_csv('final.csv', index=False)
final2 = final.sort_values(by="Final", ascending=False).copy()
final2

JobID                             title       KNN    TF-IDF        CV   
0    35  Beauty Advisor - Innisfree Store  0.333333  0.333333  0.042458  \
3   306                  Asisten Apoteker  0.000000  0.000000  0.333333   
1   304                  Host Live Tiktok  0.096300  0.096487  0.009779   
2   104   Host Live Streaming TikTok Shop  0.026454  0.026520  0.000000   

      Final  
0  0.709125  
3  0.333333  
1  0.202566  
2  0.052974

In [685]:
final2.head(10)

JobID                             title       KNN    TF-IDF        CV   
0    35  Beauty Advisor - Innisfree Store  0.333333  0.333333  0.042458  \
3   306                  Asisten Apoteker  0.000000  0.000000  0.333333   
1   304                  Host Live Tiktok  0.096300  0.096487  0.009779   
2   104   Host Live Streaming TikTok Shop  0.026454  0.026520  0.000000   

      Final  
0  0.709125  
3  0.333333  
1  0.202566  
2  0.052974

In [686]:
# final2.merge(df, on="JobID")
final_all = df.merge(final2, on="JobID")
final_job = final_all.sort_values(by="Final", ascending=False).copy()
final_job

JobID                            Posisi   
0    35  Beauty Advisor - Innisfree Store  \
3   306                  Asisten Apoteker   
2   304                  Host Live Tiktok   
1   104   Host Live Streaming TikTok Shop   

                                        Perusahaan    Lokasi   
0                                Time International  Jakarta  \
3                                Apotek Alfa Medika  Jakarta   
2                               FCOMMERCE INDONESIA  Jakarta   
1  Future Commerce Indonesia (F-Commerce Indonesia)  Jakarta   

   Salary (minimum per bulan) Tipe Pekerjaan   
0                           0      Full-time  \
3                           0      Full-time   
2                     4950000      Full-time   
1                     4000000      Full-time   

                                         Kualifikasi   
0  Maksimal umur 24 tahun \nMemiliki pengalaman d...  \
3  SMA/SMU/SMK (Diwajibkan)\nPengalaman: Asisten ...   
2  Pria/Wanita berpenampilan menarik dan berdomis...   
1  Wanita\nMemiliki pengalaman sebagai host menja...   

                                Deskripsi Pekerjaan    
0  Melayani customer dengan baik dan ramah \nDapa...  \
3  Membaca dan meracik obat\nMelayani pembelian p...   
2  Bertanggung jawab atas Live streaming sehari-h...   
1  Bertanggung jawab atas Live streaming sehari-h...   

                                                Link   
0  https://id.indeed.com/rc/clk?jk=ccfd37d043ef49...  \
3  https://id.indeed.com/company/Apotek-Alfa-Medi...   
2  https://id.indeed.com/company/FCOMMERCE-MALAYS...   
1  https://id.indeed.com/company/Future-Commerce-...   

                                                 All   
0  Beauty Advisor - Innisfree Store Time Internat...  \
3  Asisten Apoteker Apotek Alfa Medika Jakarta Fu...   
2  Host Live Tiktok FCOMMERCE INDONESIA Jakarta F...   
1  Host Live Streaming TikTok Shop Future Commerc...   

                              title       KNN    TF-IDF        CV     Final  
0  Beauty Advisor - Innisfree Store  0.333333  0.333333  0.042458  0.709125  
3                  Asisten Apoteker  0.000000  0.000000  0.333333  0.333333  
2                  Host Live Tiktok  0.096300  0.096487  0.009779  0.202566  
1   Host Live Streaming TikTok Shop  0.026454  0.026520  0.000000  0.052974