In [269]:
# CONNECT GOOGLE DRIVE WITH GOOGLE COLAB
# from google.colab import drive
# drive.mount("/content/drive")

# IMPORT LIBRARY

In [270]:
# IMPORT LIBRARY

# !pip install pdfplumber
import pdfplumber
import pandas as pd
import numpy as np
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords 
from string import punctuation
from nltk.corpus import wordnet as wn
from nltk.stem import WordNetLemmatizer
from nltk import BigramCollocationFinder
from nltk.probability import FreqDist
from heapq import nlargest
from collections import defaultdict
import pandas as pd 
from nltk.collocations import*
nltk.download('punkt')
nltk.download('stopwords')
# nltk.download('wordnet')
import pdfminer
from pdfminer.high_level import extract_text
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import MinMaxScaler

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\INES\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\INES\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


# IMPORT CV

In [271]:
# IMPORT CV

# Read PDF file and extract text
def read_pdf(file_path):
    text = extract_text(file_path)
    # print(text)
    return text
resume_path = r"C:\ikhsan\UNAIR\Template CV ATS-Friendly Glints\CV panjang.pdf"
text = read_pdf(resume_path)
print(text)

# Additional stopwords
f2=open(r"data\stopwords.txt",'r', errors = 'ignore')
text2=f2.read()
stopwords_additional = word_tokenize(text2.replace("\n", " "))

MUKHAMAD IKHSANUDIN 

Mahasiswa Aktif 

Temanggung | +62 85802754354 | ikhsan2050@gmail.com   

RINGKASAN 

Mahasiswa  aktif  dengan  berbagai  pengalaman  organisasi  dan  kepanitiaan.  Memiliki 
kemampuan  time  management,  critical  thinking,  kerjasama  tim,  berkomitmen  dan 
bertanggung  jawab.  Menguasai  bahasa  pemrograman  Python  sebagai  dasar  pembelajaran 
mesin dan aplikasi Tableau sebagai alat untuk melakukan analisis serta visualisasi data. 

PENDIDIKAN 

MBKM Studi Independen Bangkit (2023 - Sekarang) 
Machine Learning 

Universitas Airlangga (2020 - Sekarang) 
S1 Sistem Informasi – IPK 3,44/4,00 

SMA NEGERI 1 PARAKAN (2017 - 2020) 
Matematika dan IPA - NA 85,50/100,00 

PENGALAMAN ORGANISASI 

BADAN  EKSEKUTIF  MAHASISWA  (BEM)  FAKULTAS  SAINS  DAN  TEKNOLOGI 
UNIVERSITAS AIRLANGGA - Surabaya, Indonesia 
Koordinator Bidang Pergerakan (Januari 2023 – Saat ini) 

●  Membawahi 2 departemen yang masing-masing memiliki 2 divisi 
Staf Departemen Kajian dan Aksi Strategi

# CV PROCESS FUNCTION

In [272]:
def nlp(text):
    word_sent = word_tokenize(text.lower().replace("\n",""))
    _stopwords = set(stopwords.words('english', 'indonesian') + list(punctuation)+list("●")+list('–')+list('’')+stopwords_additional)
    word_sent=[word for word in word_sent if word not in _stopwords]
    lemmatizer = WordNetLemmatizer()
    NLP_Processed_CV = [lemmatizer.lemmatize(word) for word in word_tokenize(" ".join(word_sent))]
#     return " ".join(NLP_Processed_CV)
    return NLP_Processed_CV

In [273]:
def get_key_word(x):
    finder = BigramCollocationFinder.from_words(x)
    keyword = []
    keywords_CV = []
    for i in sorted(finder.ngram_fd.items()):
    # if a double word appears more than once, then print it out.
        if i[1] > 1:
            print(i)
            keyword.append(i[0])
        else:
            pass
    # print("************************")
    for j in keyword:
    #     print(" ".join(j))
        keywords_CV.append(" ".join(j))
    return keywords_CV

In [274]:
NLP_Processed_CV = nlp(text)
NLP_Processed_CV
key_word = get_key_word(NLP_Processed_CV)
key_word

(('2021', 'desember'), 2)
(('2021', 'latihan'), 2)
(('2021', 'menjadi'), 2)
(('2021', '•'), 5)
(('2022', 'desember'), 2)
(('2022', '•'), 2)
(('airlangga', '2021'), 10)
(('airlangga', '2022'), 3)
(('airlangga', 'surabaya'), 3)
(('atau', 'pelatihan'), 3)
(('bahasa', 'pemrograman'), 2)
(('bem', 'fakultas'), 2)
(('dakwah', 'kampus'), 5)
(('dan', 'dokumentasi'), 2)
(('dan', 'kepemimpinan'), 2)
(('dan', 'teknologi'), 8)
(('desain', 'dan'), 2)
(('desember', '2021'), 2)
(('desember', '2022'), 2)
(('fakultas', 'sains'), 8)
(('februari', '2021'), 2)
(('jimm', 'fakultas'), 3)
(('kepemimpinan', 'pendaki'), 2)
(('keterampilan', 'manajemen'), 2)
(('latihan', 'keterampilan'), 2)
(('machine', 'learning'), 2)
(('mahasiswa', 'aktif'), 2)
(('mahasiswa', 'muslim'), 2)
(('mahasiswa', 'tingkat'), 2)
(('manajemen', 'mahasiswa'), 2)
(('menjadi', 'penanggung'), 2)
(('pelatihan', 'dakwah'), 6)
(('pemrograman', 'python'), 2)
(('penanggung', 'jawab'), 3)
(('pengalaman', 'organisasi'), 2)
(('program', 'kerja'), 3)

['2021 desember',
 '2021 latihan',
 '2021 menjadi',
 '2021 •',
 '2022 desember',
 '2022 •',
 'airlangga 2021',
 'airlangga 2022',
 'airlangga surabaya',
 'atau pelatihan',
 'bahasa pemrograman',
 'bem fakultas',
 'dakwah kampus',
 'dan dokumentasi',
 'dan kepemimpinan',
 'dan teknologi',
 'desain dan',
 'desember 2021',
 'desember 2022',
 'fakultas sains',
 'februari 2021',
 'jimm fakultas',
 'kepemimpinan pendaki',
 'keterampilan manajemen',
 'latihan keterampilan',
 'machine learning',
 'mahasiswa aktif',
 'mahasiswa muslim',
 'mahasiswa tingkat',
 'manajemen mahasiswa',
 'menjadi penanggung',
 'pelatihan dakwah',
 'pemrograman python',
 'penanggung jawab',
 'pengalaman organisasi',
 'program kerja',
 'publikasi desain',
 'sains dan',
 'ski di',
 'staf departemen',
 'staf publikasi',
 'surabaya indonesia',
 'teknologi universitas',
 'ukmki universitas',
 'universitas airlangga',
 '• basic',
 '• koordinator',
 '• staf']

# IMPORT JOB DATA

In [275]:
#Import scraped data
df = pd.read_excel(r"data\data website indeed Jakarta (30 May 2023) last.xlsx", "Part-Time")
index = []
for i in range (0, len(df)):
    index.append(i)
df.insert(0,'JobID', index)
df['All'] = df['Posisi'] + ' ' + df['Perusahaan '] + ' ' + df['Lokasi'] + ' ' + df['Tipe Pekerjaan'] + ' ' + df['Kualifikasi'] + ' ' + df['Deskripsi Pekerjaan ']
df.rename(columns = {'Perusahaan ':'Perusahaan', 'Deskripsi Pekerjaan ': 'Deskripsi Pekerjaan'}, inplace = True)
df.shape
df.info()
df.head(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype 
---  ------                      --------------  ----- 
 0   JobID                       74 non-null     int64 
 1   Posisi                      74 non-null     object
 2   Perusahaan                  74 non-null     object
 3   Lokasi                      74 non-null     object
 4   Salary (minimum per bulan)  74 non-null     int64 
 5   Tipe Pekerjaan              74 non-null     object
 6   Kualifikasi                 74 non-null     object
 7   Deskripsi Pekerjaan         41 non-null     object
 8   Link                        74 non-null     object
 9   All                         41 non-null     object
dtypes: int64(2), object(8)
memory usage: 5.9+ KB


JobID                               Posisi                 Perusahaan   
0      0  Talent Host Streaming ( Freelance )  THE AESTHETIC SKIN CLINIC  \
1      1                         Data Analyst                   Peroptyx   

    Lokasi  Salary (minimum per bulan) Tipe Pekerjaan   
0  Jakarta                           0      Part-time  \
1  Jakarta                     1653356      Part-time   

                                         Kualifikasi   
0  Wanita\nUsia maksimal 30 tahun\nMemiliki penga...  \
1  Technical requirements to perform the work\nAc...   

                                 Deskripsi Pekerjaan   
0  Melakukan penjualan produk secara live di Tik ...  \
1  Work up to 20 hours per week.\nEarn a competit...   

                                                Link   
0  https://id.indeed.com/company/The-Aesthetic-Sk...  \
1  https://id.indeed.com/pagead/clk?mo=r&ad=-6NYl...   

                                                 All  
0  Talent Host Streaming ( Freelance ) THE AESTHE...  
1  Data Analyst Peroptyx Jakarta Part-time Techni...

# TRAINING JOB DATA

In [276]:
# TRAINING DATA
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(decode_error='replace', encoding='utf-8', stop_words=stopwords.words('english', 'indonesian'))
tfidf_jobid = tfidf_vectorizer.fit_transform(df['All'].apply(lambda x: np.str_(x)))
# print(tfidf_jobid)
user_tfidf = tfidf_vectorizer.transform(df['All'].apply(lambda x: np.str_(x)))
# print(user_tfidf)

cos_similarity_tfidf = map(lambda x: cosine_similarity(user_tfidf,x),tfidf_jobid)
outputJob = list(cos_similarity_tfidf)
outputJob

[array([[1.        ],
        [0.01759701],
        [0.        ],
        [0.42952797],
        [0.0127131 ],
        [0.18980101],
        [0.22322252],
        [0.        ],
        [0.16146738],
        [0.        ],
        [0.16545935],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.00897871],
        [0.0576396 ],
        [0.        ],
        [0.12215533],
        [0.01065538],
        [0.01419572],
        [0.        ],
        [0.0464339 ],
        [0.09294668],
        [0.08646597],
        [0.01127627],
        [0.12571594],
        [0.14467924],
        [0.15680985],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.21119465],
        [0.14902721],
        [0.        ],
        [0.23350516],
        [0.        ],
        [0.00485696],
        [0.00812573],
        [0.        ],
        [0.0059325 ],
        [0.        ],
        [0.00866997],
        [0.        ],
        [0.        ],
        [0

In [277]:
df2 = pd.DataFrame()

# append columns to an empty DataFrame
df2['Posisi'] = ["I"]
df2['Deskripsi Pekerjaan'] = ["I"]
df2['Perusahaan'] = ["I"]

# Compare with the key words from CV only
df2['All'] = " ".join(key_word)
df2.head()
# Compare with the entire CV
# df2['All'] = " ".join(NLP_Processed_CV)
# df2

Posisi Deskripsi Pekerjaan Perusahaan   
0      I                   I          I  \

                                                 All  
0  2021 desember 2021 latihan 2021 menjadi 2021 •...

# RECOMMENDATION FUNCTION

In [278]:
def get_recommendation(top, df_all, scores):
    recommendation = pd.DataFrame(columns = ['JobID',  'Posisi', 'Perusahaan', 'Deskripsi Pekerjaan','Score'])
    count = 0
    for i in top:
#         recommendation.at[count, 'ApplicantID'] = u
        recommendation.at[count, 'JobID'] = df.index[i]
        recommendation.at[count, 'Posisi'] = df['Posisi'][i]
        recommendation.at[count, 'Perusahaan'] = df['Perusahaan'][i]
#         recommendation.at[count, 'location'] = df['location'][i]
        recommendation.at[count, 'Deskripsi Pekerjaan'] = df['Deskripsi Pekerjaan'][i]
        recommendation.at[count, 'Score'] =  scores[count]
        count += 1
    return recommendation

def get_top(outputData):
    if outputData.__class__ == tuple:
        top = outputData[1][0][0:]
        list_scores = outputData[0][0][0:]
    else:
        top = sorted(range(len(outputData)), key=lambda i: outputData[i], reverse=True)[:100]
        list_scores = [outputData[i][0][0] for i in top]
    return top, list_scores

In [279]:
# TFIDF
def TFIDF(scraped_data, cv):
    tfidf_vectorizer = TfidfVectorizer(decode_error='replace', encoding='utf-8', stop_words=stopwords.words('english', 'indonesian'))

    # TF-IDF Scraped data
    tfidf_jobid = tfidf_vectorizer.fit_transform(scraped_data.apply(lambda x: np.str_(x)))

    # TF-IDF CV
    user_tfidf = tfidf_vectorizer.transform(cv.apply(lambda x: np.str_(x)))

    # Using cosine_similarity on (Scraped data) & (CV)
    cos_similarity_tfidf = map(lambda x: cosine_similarity(user_tfidf,x),tfidf_jobid)

    outputTF = list(cos_similarity_tfidf)
    return outputTF

In [280]:
# COUNTVECTOR
def count_vectorize(scraped_data, cv):
    count_vectorizer = CountVectorizer(decode_error='replace', encoding='utf-8', stop_words=stopwords.words('english', 'indonesian'))
    # CountV the scraped data
    count_jobid = count_vectorizer.fit_transform(scraped_data.apply(lambda x: np.str_(x)))

    # CountV the cv
    user_count = count_vectorizer.transform(cv.apply(lambda x: np.str_(x)))
    
    # Using cosine_similarity on (Scraped data) & (CV)
    cos_similarity_countv = map(lambda x: cosine_similarity(user_count, x),count_jobid)
    
    output3 = list(cos_similarity_countv)
    return output3

In [281]:
# KNN
def KNN(scraped_data, cv):
    tfidf_vectorizer = TfidfVectorizer(decode_error='replace', encoding='utf-8', stop_words=stopwords.words('english', 'indonesian'))
    # n_neighbors = 100
    KNN = NearestNeighbors(n_neighbors=10)
    KNN.fit(tfidf_vectorizer.fit_transform(scraped_data.apply(lambda x: np.str_(x))))
#     NNs = KNN.kneighbors(tfidf_vectorizer.transform(cv), return_distance=True)
    NNs = KNN.kneighbors(tfidf_vectorizer.transform(cv.apply(lambda x: np.str_(x))))
    # knn = get_recommendation(top, df, index_score)
    return NNs

# CV TEST WITH TF-IDF, COUNT VECTORIZER, KNN 

In [282]:
outputTF = TFIDF(df['All'], df2['All'])
outputTF

[array([[0.10602386]]),
 array([[0.01007192]]),
 array([[0.]]),
 array([[0.10919226]]),
 array([[0.02735785]]),
 array([[0.12121107]]),
 array([[0.08383914]]),
 array([[0.]]),
 array([[0.12641443]]),
 array([[0.]]),
 array([[0.04864258]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.03423539]]),
 array([[0.]]),
 array([[0.04789987]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.06445032]]),
 array([[0.04610517]]),
 array([[0.01551759]]),
 array([[0.03449948]]),
 array([[0.]]),
 array([[0.0646013]]),
 array([[0.08687213]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.18754359]]),
 array([[0.16981994]]),
 array([[0.]]),
 array([[0.09293391]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.0241131]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.02732298]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.01755923]]),
 array([[0.]]),
 array([[0.12762861]]),
 array([[0.02470514]]),
 array([[0

In [283]:
outputCV = count_vectorize(df['All'], df2['All'])
outputCV

[array([[0.27311943]]),
 array([[0.01623069]]),
 array([[0.]]),
 array([[0.17774487]]),
 array([[0.03030246]]),
 array([[0.31092553]]),
 array([[0.21381408]]),
 array([[0.]]),
 array([[0.34688699]]),
 array([[0.]]),
 array([[0.12813636]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.10510605]]),
 array([[0.]]),
 array([[0.14630143]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.14714847]]),
 array([[0.14997924]]),
 array([[0.0221187]]),
 array([[0.03156365]]),
 array([[0.]]),
 array([[0.06274064]]),
 array([[0.23352251]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.40026415]]),
 array([[0.2606289]]),
 array([[0.]]),
 array([[0.23265058]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.02401634]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.02453849]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.02509626]]),
 array([[0.]]),
 array([[0.33597529]]),
 array([[0.02833461]]),
 array([[0

In [284]:
# outputKNN = KNN(df['All'], df2['All'])
# outputKNN
outputKNN = KNN(df['All'], df2['All'])
outputKNN

(array([[1.27472068, 1.28854962, 1.30706089, 1.32088712, 1.32180601,
         1.32299628, 1.32573673, 1.3347717 , 1.33714333, 1.343046  ]]),
 array([[32, 33, 72, 48,  8, 55,  5,  3,  0, 73]], dtype=int64))

In [285]:
top, list_score = get_top(outputTF)
finalTF = get_recommendation(top, df, list_score)
finalTF

JobID                                Posisi                     Perusahaan   
0     32  Sales Promotion Untuk Sekolah Coding         PT. Timedoor Indonesia  \
1     33                     Programmer Intern   PT Sinergy Informasi Pratama   
2     72                               Barista        Serantau Coffee x Space   
3     48                     Sales Acquisition       PT ROMAJU Persona Unggul   
4      8           ADMIN SERVICE JAKARTA BARAT  PT.KHARISMA POTENSA INDONESIA   
..   ...                                   ...                            ...   
69    67        Ambassador SOKO FInancial Club                 Soko Financial   
70    68                    Guru TK SD SMP SMA            HomeSchooling Logos   
71    69          Internship - Corporate Legal                 Prudential plc   
72    70                                  COOK           dots board game cafe   
73    71    Internship - Bancassurance Project                 Prudential plc   

                                  Deskripsi Pekerjaan     Score  
0   Menjaga area booth sesuai tempat dan durasi ya...  0.187544  
1   Melakukan pengembangan aplikasi internal\nMela...   0.16982  
2   Menemui pelanggan dan memberi informasi kepada...  0.145796  
3   Analisa pasar dan mengimplementasikan strategi...  0.127629  
4   Bertanggungjawab atas pengecekkan dokumen dan ...  0.126414  
..                                                ...       ...  
69                                                NaN       0.0  
70                                                NaN       0.0  
71  Assisting Legal and Company Secretary team in ...       0.0  
72                                                NaN       0.0  
73  Encompassing all aspect of setting up Bancassu...       0.0  

[74 rows x 5 columns]

In [286]:
top, list_score = get_top(outputCV)
finalCV = get_recommendation(top, df, list_score)
finalCV

JobID                                Posisi                     Perusahaan   
0     32  Sales Promotion Untuk Sekolah Coding         PT. Timedoor Indonesia  \
1      8           ADMIN SERVICE JAKARTA BARAT  PT.KHARISMA POTENSA INDONESIA   
2     72                               Barista        Serantau Coffee x Space   
3     48                     Sales Acquisition       PT ROMAJU Persona Unggul   
4      5                       Desk Collection                       Indodana   
..   ...                                   ...                            ...   
69    67        Ambassador SOKO FInancial Club                 Soko Financial   
70    68                    Guru TK SD SMP SMA            HomeSchooling Logos   
71    69          Internship - Corporate Legal                 Prudential plc   
72    70                                  COOK           dots board game cafe   
73    71    Internship - Bancassurance Project                 Prudential plc   

                                  Deskripsi Pekerjaan     Score  
0   Menjaga area booth sesuai tempat dan durasi ya...  0.400264  
1   Bertanggungjawab atas pengecekkan dokumen dan ...  0.346887  
2   Menemui pelanggan dan memberi informasi kepada...  0.337393  
3   Analisa pasar dan mengimplementasikan strategi...  0.335975  
4   Kumpulkan pembayaran dari pelanggan melalui Pa...  0.310926  
..                                                ...       ...  
69                                                NaN       0.0  
70                                                NaN       0.0  
71  Assisting Legal and Company Secretary team in ...       0.0  
72                                                NaN       0.0  
73  Encompassing all aspect of setting up Bancassu...       0.0  

[74 rows x 5 columns]

In [287]:
# top = outputKNN[1][0][0:]
# list_score = outputKNN[0][0][0:]
top, list_score = get_top(outputKNN)
finalKNN = get_recommendation(top, df, list_score)
finalKNN

JobID                                Posisi                     Perusahaan   
0    32  Sales Promotion Untuk Sekolah Coding         PT. Timedoor Indonesia  \
1    33                     Programmer Intern   PT Sinergy Informasi Pratama   
2    72                               Barista        Serantau Coffee x Space   
3    48                     Sales Acquisition       PT ROMAJU Persona Unggul   
4     8           ADMIN SERVICE JAKARTA BARAT  PT.KHARISMA POTENSA INDONESIA   
5    55                     Part-Time Teacher               Kukche Languages   
6     5                       Desk Collection                       Indodana   
7     3      Host Live Streaming Tik Tok Shop   PT Eramas Agri Internasional   
8     0   Talent Host Streaming ( Freelance )      THE AESTHETIC SKIN CLINIC   
9    73          SPG - PIK (Produk non halal)     PT. Bali Highlands Organik   

                                 Deskripsi Pekerjaan     Score  
0  Menjaga area booth sesuai tempat dan durasi ya...  1.274721  
1  Melakukan pengembangan aplikasi internal\nMela...   1.28855  
2  Menemui pelanggan dan memberi informasi kepada...  1.307061  
3  Analisa pasar dan mengimplementasikan strategi...  1.320887  
4  Bertanggungjawab atas pengecekkan dokumen dan ...  1.321806  
5  Memberikan pengajaran bahasa asing sesuai deng...  1.322996  
6  Kumpulkan pembayaran dari pelanggan melalui Pa...  1.325737  
7  Menjadi host selama berjalannya live streaming...  1.334772  
8  Melakukan penjualan produk secara live di Tik ...  1.337143  
9  Mempromosikan dan merekomendasikan produk kepa...  1.343046

# MERGE SCORE

In [288]:
merge1 = finalKNN[['JobID','Posisi', 'Score']].merge(finalTF[['JobID','Score']], on= "JobID")
final = merge1.merge(finalCV[['JobID','Score']], on = "JobID")
final = final.rename(columns={"Score_x": "KNN", "Score_y": "TF-IDF","Score": "CV"})
final.head()

JobID                                Posisi       KNN    TF-IDF        CV
0    32  Sales Promotion Untuk Sekolah Coding  1.274721  0.187544  0.400264
1    33                     Programmer Intern   1.28855   0.16982  0.260629
2    72                               Barista  1.307061  0.145796  0.337393
3    48                     Sales Acquisition  1.320887  0.127629  0.335975
4     8           ADMIN SERVICE JAKARTA BARAT  1.321806  0.126414  0.346887

In [289]:
# SCALE
slr = MinMaxScaler()
final[["KNN", "TF-IDF", 'CV']] = slr.fit_transform(final[["KNN", "TF-IDF", 'CV']])

# Multiply by weights
final['KNN'] = (1-final['KNN'])/3
final['TF-IDF'] = final['TF-IDF']/3
final['CV'] = final['CV']/3
final['Final'] = final['KNN']+final['TF-IDF']+final['CV']
final.sort_values(by="Final", ascending=False)

JobID                                Posisi       KNN    TF-IDF        CV   
0    32  Sales Promotion Untuk Sekolah Coding  0.333333  0.333333  0.333333  \
1    33                     Programmer Intern  0.265867  0.267272  0.124160   
2    72                               Barista  0.175558  0.177727  0.239153   
4     8           ADMIN SERVICE JAKARTA BARAT  0.103622  0.105486  0.253374   
3    48                     Sales Acquisition  0.108105  0.110011  0.237029   
6     5                       Desk Collection  0.084445  0.086091  0.199504   
5    55                     Part-Time Teacher  0.097815  0.099619  0.050562   
8     0   Talent Host Streaming ( Freelance )  0.028797  0.029484  0.142871   
7     3      Host Live Streaming Tik Tok Shop  0.040367  0.041293  0.000000   
9    73          SPG - PIK (Produk non halal)  0.000000  0.000000  0.046028   

      Final  
0  1.000000  
1  0.657299  
2  0.592437  
4  0.462482  
3  0.455145  
6  0.370041  
5  0.247996  
8  0.201151  
7  0.081660  
9  0.046028

In [290]:
final_all = df.merge(final, on="JobID")
final_job = final_all.sort_values(by="Final", ascending=False).copy()
final_job

JobID                              Posisi_x                     Perusahaan   
4    32  Sales Promotion Untuk Sekolah Coding         PT. Timedoor Indonesia  \
5    33                     Programmer Intern   PT Sinergy Informasi Pratama   
8    72                               Barista        Serantau Coffee x Space   
3     8           ADMIN SERVICE JAKARTA BARAT  PT.KHARISMA POTENSA INDONESIA   
6    48                     Sales Acquisition       PT ROMAJU Persona Unggul   
2     5                       Desk Collection                       Indodana   
7    55                     Part-Time Teacher               Kukche Languages   
0     0   Talent Host Streaming ( Freelance )      THE AESTHETIC SKIN CLINIC   
1     3      Host Live Streaming Tik Tok Shop   PT Eramas Agri Internasional   
9    73          SPG - PIK (Produk non halal)     PT. Bali Highlands Organik   

    Lokasi  Salary (minimum per bulan) Tipe Pekerjaan   
4  Jakarta                           0      Part-time  \
5  Jakarta                     1500000      Part-time   
8  Jakarta                     1500000      Part-time   
3  Jakarta                     4600000      Part-time   
6  Jakarta                     5100000      Part-time   
2  Jakarta                           0      Part-time   
7  Jakarta                           0      Part-time   
0  Jakarta                           0      Part-time   
1  Jakarta                     2500000      Part-time   
9  Jakarta                     4000000      Part-time   

                                         Kualifikasi   
4  Keterampilan komunikasi dan negosiasi dalam me...  \
5  Testing dan debugging\nDesain dan dokumentasi\...   
8   Pria/Wanita berumur maksimal 35 tahun pertang...   
3  Pendidikan minimal SMA/SMK atau Diploma\nUsia ...   
6  Minimal Pendidikan SMA atau sederajat\nMemilik...   
2  Pendidikan Min. SMA/K\nSetidaknya 6 bulan peng...   
7  Pria/Wanita, usia 20-40 tahun. Sehat jasmani d...   
0  Wanita\nUsia maksimal 30 tahun\nMemiliki penga...   
1  Maksimal usia 25 Tahun\nPendidikan Terakhir SM...   
9  Wanita, Pendidikan minimal SMA/SMK. Maksimal u...   

                                 Deskripsi Pekerjaan   
4  Menjaga area booth sesuai tempat dan durasi ya...  \
5  Melakukan pengembangan aplikasi internal\nMela...   
8  Menemui pelanggan dan memberi informasi kepada...   
3  Bertanggungjawab atas pengecekkan dokumen dan ...   
6  Analisa pasar dan mengimplementasikan strategi...   
2  Kumpulkan pembayaran dari pelanggan melalui Pa...   
7  Memberikan pengajaran bahasa asing sesuai deng...   
0  Melakukan penjualan produk secara live di Tik ...   
1  Menjadi host selama berjalannya live streaming...   
9  Mempromosikan dan merekomendasikan produk kepa...   

                                                Link   
4  https://id.indeed.com/company/PT.-Timedoor-Ind...  \
5  https://id.indeed.com/company/PT-SINERGY-INFOR...   
8  https://id.indeed.com/company/Serantau-Coffee/...   
3  https://id.indeed.com/company/PT.KHARISMA-POTE...   
6  https://id.indeed.com/company/PT-Romaju-Person...   
2  https://id.indeed.com/rc/clk?jk=809fcfdca53881...   
7  https://id.indeed.com/rc/clk?jk=8d3684e4ea4a19...   
0  https://id.indeed.com/company/The-Aesthetic-Sk...   
1  https://id.indeed.com/company/PT-Eramas-Agri-I...   
9  https://id.indeed.com/company/PT.-Bali-Highlan...   

                                                 All   
4  Sales Promotion Untuk Sekolah Coding PT. Timed...  \
5  Programmer Intern PT Sinergy Informasi Pratama...   
8  Barista Serantau Coffee x Space Jakarta Part-t...   
3  ADMIN SERVICE JAKARTA BARAT PT.KHARISMA POTENS...   
6  Sales Acquisition PT ROMAJU Persona Unggul Jak...   
2  Desk Collection Indodana Jakarta Part-time Pen...   
7  Part-Time Teacher Kukche Languages Jakarta Par...   
0  Talent Host Streaming ( Freelance ) THE AESTHE...   
1  Host Live Streaming Tik Tok Shop PT Eramas Agr...   
9  SPG - PIK (Produk non halal) PT. Bali Highland...   

                         

# EXPORT TO PICKLE

In [291]:
import pickle
pickle.dump(finalTF, open('artifacts/TF.pkl', 'wb'))
pickle.dump(finalCV, open('artifacts/cv.pkl', 'wb'))
pickle.dump(finalKNN, open('artifacts/knn.pkl', 'wb'))
pickle.dump(final, open('artifacts/final.pkl', 'wb'))
pickle.dump(final_job, open('artifacts/final_job.pkl', 'wb'))